version: 2

sources:
  - name: staging
    schema: crypto_data_project_raw_tables
    database: dtc-de-updated
    tables:
      - name: BTC_*
      - name: ETH_*
      - name: LTC_*
      - name: XRP_*
      - name: ENS_*