version: 2

models:
  - name: core_crypto_open_prices
    meta:
      materialized: view
      schema: data_core
    description: >
      A core model that joins data from stg_btc, stg_ltc, stg_xrp, stg_ens, and stg_eth.
    columns:
      - name: date
        description: The date for which the prices are reported.
      - name: btc_daily_price_open
        description: The opening price of Bitcoin on the given date.
      - name: xrp_daily_price_open
        description: The opening price of XRP on the given date.
      - name: eth_daily_price_open
        description: The opening price of Ethereum on the given date.
      - name: ens_daily_price_open
        description: The opening price of ENS on the given date.
      - name: ltc_daily_price_open
        description: The opening price of Litecoin on the given date.
  - name: core_crypto_usd_volume
    meta:
      materialized: view
      schema: data_core
    description: >
      A core model that joins data from stg_btc, stg_ltc, stg_xrp, stg_ens, and stg_eth.
    columns:
      - name: date
        description: The date for which the prices are reported.
      - name: btc_usd_volume
        description: The volume of Bitcoin traded in USD on the given date.
      - name: xrp_usd_volume
        description: The volume of XRP traded in USD on the given date.
      - name: eth_usd_volume
        description: The volume of Ethereum traded in USD on the given date.
      - name: ens_usd_volume
        description: The volume of ENS traded in USD on the given date.
      - name: ltc_usd_volume
        description: The volume of Litecoin traded in USD on the given date.
